language: node_js

node_js:
  - '11.3.0'

cache:
  directories:
    - node_modules

script:
  - npm run test
  - npm run build:site

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: deploy
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: site
        on:
          branch: master

